[profile.release]
panic = "unwind"

[workspace]
resolver = "2"

exclude = [
	"vendor/webpki",
	"vendor/ring",
	"polkadot/node/service",
]

members = [
	"node",
	"parachains-common",
	"crates/phala-types",
	"crates/phala-mq",
	"crates/phala-node-rpc-ext",
	"crates/phala-node-rpc-ext/types",
	"crates/prpc",
	"crates/phala-trie-storage",
	"substrate/frame/utility",
	"pallets/phala",
	"pallets/phala/mq-runtime-api",
	"pallets/xtransfer",
	"pallets/parachain-info",
	"runtime/khala",
	"runtime/thala",
]

[patch."https://github.com/paritytech/polkadot"]
polkadot-service = { path = "polkadot/node/service" }
